var namespacenet_1_1javaguides_1_1springboot_1_1service_1_1room_record =
[
    [ "RoomRecordService", "interfacenet_1_1javaguides_1_1springboot_1_1service_1_1room_record_1_1_room_record_service.html", "interfacenet_1_1javaguides_1_1springboot_1_1service_1_1room_record_1_1_room_record_service" ],
    [ "RoomRecordServiceImpl", "classnet_1_1javaguides_1_1springboot_1_1service_1_1room_record_1_1_room_record_service_impl.html", "classnet_1_1javaguides_1_1springboot_1_1service_1_1room_record_1_1_room_record_service_impl" ]
];