var namespacenet_1_1javaguides_1_1springboot_1_1service_1_1notification =
[
    [ "NotificationService", "interfacenet_1_1javaguides_1_1springboot_1_1service_1_1notification_1_1_notification_service.html", "interfacenet_1_1javaguides_1_1springboot_1_1service_1_1notification_1_1_notification_service" ],
    [ "NotificationServiceImpl", "classnet_1_1javaguides_1_1springboot_1_1service_1_1notification_1_1_notification_service_impl.html", "classnet_1_1javaguides_1_1springboot_1_1service_1_1notification_1_1_notification_service_impl" ]
];