var namespacenet_1_1javaguides_1_1springboot_1_1service_1_1reservation =
[
    [ "ReservationService", "interfacenet_1_1javaguides_1_1springboot_1_1service_1_1reservation_1_1_reservation_service.html", "interfacenet_1_1javaguides_1_1springboot_1_1service_1_1reservation_1_1_reservation_service" ],
    [ "ReservationServiceImpl", "classnet_1_1javaguides_1_1springboot_1_1service_1_1reservation_1_1_reservation_service_impl.html", "classnet_1_1javaguides_1_1springboot_1_1service_1_1reservation_1_1_reservation_service_impl" ]
];